name: test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: [self-hosted, test]

    steps:
      - name: docker test
        run: docker run -d --name test python:3.11 sleep infinity